all:
  children:
    europe:
      hosts:
        mvm:
        # server1 ansible_host=192.168.77.20 ansible_user=root ansible_ssh_pass=password ansible_ssh_port=22
#    america:
#      hosts:
#        l.deb2:
#    apac:
#      hosts:
#        l.deb3:

