# ansible-playbook -u root playbooks/02.install_stack.yaml
---
- hosts: all
  name: LookingGlass Stack installation takes a while
  gather_facts: yes
  become: yes
  tasks:

    - name: Install necessary LG stack
      ansible.builtin.package:
        name:
          - mtr-tiny
          - curl
          - traceroute
          - bind9-host
          - nginx
          - uwsgi
          - python3
          - python3-pip
          - python3-venv
          - python3-virtualenv
          - virtualenv
          - uwsgi-plugin-python3
        state: latest

    - name: Create the lg user - disabled password login
      user:
        name: lg
        password: !
        state: present
        shell: /bin/bash
        system: no
        createhome: yes